### ISSUE TITLE
React-Redux Group Project detail

### ISSUE THREAD

**Issue by Whoistolu** [Whoistolu/Space-Traveler-Hub#25]
# React-Redux Group Project detail

## Project link:
- https://github.com/Whoistolu/Space-Traveler-Hub/

## Team
- Two members (2)
- @luqmanmusah and @Whoistolu

**Comment by omar-labana** [comment]
Hi @Whoistolu and @luqmanmusah , 

Your project is complete!  There is nothing else to say other than... it's time to start you project! 👏
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
